# Generated by Django 3.0.1 on 2019-12-28 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='donate',
        ),
        migrations.DeleteModel(
            name='Donate',
        ),
    ]
